import argparse
import json
import sys
from rich.console import Console
from rich.table import Table
from rich.panel import Panel
from rich.layout import Layout
from rich.text import Text
from .engine import ContextEngine

console = Console()

def main():
    parser = argparse.ArgumentParser(description="Audit Rust ClawOC Context Dumps")
    subparsers = parser.add_subparsers(dest="command", required=True)

    audit_parser = subparsers.add_parser("audit", help="Audit a single context dump file")
    audit_parser.add_argument("file", help="Path to debug_context.json")

    args = parser.parse_args()

    if args.command == "audit":
        try:
            with open(args.file, 'r') as f:
                data = json.load(f)
            engine = ContextEngine(data)
            report = engine.run_audit()
            print_report(report)
        except Exception as e:
            console.print(f"[red]Error: {e}[/red]")

def print_report(report):
    layout = Layout()
    layout.split_column(
        Layout(name="header", size=3),
        Layout(name="main", ratio=1),
        Layout(name="footer", size=3)
    )
    
    total = report.total_tokens
    max_t = report.max_tokens
    layout["header"].update(Panel(f"[bold cyan]Claw-Context Audit[/bold cyan] | Total Tokens: [bold yellow]{total}/{max_t}[/bold yellow]", style="white"))

    # Issues Panel
    issues_text = "\n".join([f"- {i}" for i in report.completeness_issues]) if report.completeness_issues else "[green]No completeness issues found.[/green]"
    issue_panel = Panel(issues_text, title="[bold red]Completeness Audit[/bold red]")

    # Timeline Panel
    timeline_text = Text()
    max_tokens = max((t.tokens for t in report.turns), default=1)
    for t in report.turns:
        bar_len = int((t.tokens / max_tokens) * 40)
        bar = "█" * bar_len
        color = "red" if t.tokens > 2000 else "green"
        if t.is_redundant:
            color = "yellow"
        timeline_text.append(f"{t.index:02d} [{t.role[:4]}] {bar} ({t.tokens}) {t.redundancy_reason}\n", style=color)
    timeline_panel = Panel(timeline_text, title="[bold blue]Token Timeline[/bold blue]")

    # Resource Usage Panel (Updated)
    res_table = Table(title="Top Resource Consumers")
    res_table.add_column("Type", style="cyan", width=8)
    res_table.add_column("Identifier", style="white")
    res_table.add_column("Tokens", style="yellow", justify="right")
    res_table.add_column("Count", style="green", justify="right")
    
    # Sort by total tokens consumed
    sorted_resources = sorted(report.resource_usage_summary.values(), key=lambda r: r.tokens, reverse=True)
    
    for r in sorted_resources[:8]: # Show top 8
        identifier = (r.identifier[:40] + '...') if len(r.identifier) > 40 else r.identifier
        res_table.add_row(r.resource_type, identifier, str(r.tokens), str(r.count))
        
    res_panel = Panel(res_table, title="[bold magenta]Resource Usage Analysis[/bold magenta]")

    layout["main"].split_row(
        Layout(timeline_panel, ratio=1),
        Layout(name="right_col", ratio=1)
    )
    layout["right_col"].split_column(issue_panel, res_panel)
    
    layout["footer"].update(Panel("[dim]Generated by context-profiler v0.3[/dim]", style="grey50"))

    console.print(layout)

if __name__ == "__main__":
    main()
