from typing import List, Dict, Any, Optional
from enum import Enum
from pydantic import BaseModel, Field

class MessageRole(str, Enum):
    SYSTEM = "system"
    USER = "user"
    ASSISTANT = "assistant"
    TOOL = "tool"
    UNKNOWN = "unknown"

class ContextMessage(BaseModel):
    """Normalized representation of a single message in the context."""
    id: str = Field(default_factory=lambda: "msg_" + str(abs(hash(str(id))))) # Simplified generation
    role: MessageRole
    content: str
    tool_name: Optional[str] = None
    tool_args: Optional[Dict[str, Any]] = None
    token_count: int = 0
    raw_data: Optional[Dict[str, Any]] = None

class OptimizationSuggestion(BaseModel):
    """A suggestion generated by a Rule."""
    rule_id: str
    severity: str # "INFO", "WARNING", "CRITICAL"
    target_message_index: int
    description: str
    actionable_advice: str
    estimated_savings_tokens: int
    
class AnalysisReport(BaseModel):
    total_tokens: int
    total_messages: int
    suggestions: List[OptimizationSuggestion]
    health_score: int # 0-100
